name: Docker Image CI

on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: influweb-v2
  GKE_ZONE: europe-west1-d
  DEPLOYMENT_NAME: web-client

jobs:
  build:
    name: Build, Publish, and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags

    # Build and push image to Dockerhub
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build --build-arg ENV_FILE=env-sample.config . --file Dockerfile --tag ${{secrets.DOCKER_ORGANIZATION}}/${{secrets.DOCKER_REPO_NAME}}:${GITHUB_SHA}
    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_ORGANIZATION}}/${{secrets.DOCKER_REPO_NAME}}:${GITHUB_SHA}

    # Deploy to GKE
    ## Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    ## Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    ## Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=${{secrets.DOCKER_ORGANIZATION}}/${{secrets.DOCKER_REPO_NAME}}:${GITHUB_SHA} -n italy
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n italy
